const ProgIrs = [
    {
      semester_aktif: "1",
      sks: "22",
      status_konfirmasi: "Disetujui",
      file: "Link Here",
    },
    {
      semester_aktif: "2",
      sks: "24",
      status_konfirmasi: "Disetujui",
      file: "Link Here",
    },
    {
      semester_aktif: "3",
      sks: "18",
      status_konfirmasi: "Disetujui",
      file: "Link Here",
    },
    {
      semester_aktif: "4",
      sks: "21",
      status_konfirmasi: "Disetujui",
      file: "Link Here",
    },
    {
      semester_aktif: "5",
      sks: "20",
      status_konfirmasi: "Belum Disetujui",
      file: "Link Here",
    },
    {
      semester_aktif: "6",
      sks: "22",
      status_konfirmasi: "Disetujui",
      file: "Link Here",
    },
    {
      semester_aktif: "7",
      sks: "18",
      status_konfirmasi: "Disetujui",
      file: "Link Here",
    },
    {
      semester_aktif: "8",
      sks: "13",
      status_konfirmasi: "Disetujui",
      file: "Link Here",
    },
    // {
    //   semester_aktif: "9",
    //   sks: "-",
    //   status_konfirmasi: "Disetujui",
    //   file: "Link Here",
    // },
    // {
    //   semester_aktif: "10",
    //   sks: "-",
    //   status_konfirmasi: "Belum Disetujui",
    //   file: "Link Here",
    // },
    // {
    //   semester_aktif: "11",
    //   sks: "-",
    //   status_konfirmasi: "Disetujui",
    //   file: "Link Here",
    // },
    // {
    //   semester_aktif: "12",
    //   sks: "-",
    //   status_konfirmasi: "Disetujui",
    //   file: "Link Here",
    // },
    // {
    //   semester_aktif: "13",
    //   sks: "-",
    //   status_konfirmasi: "Disetujui",
    //   file: "Link Here",
    // },
    // {
    //   semester_aktif: "14",
    //   sks: "-",
    //   status_konfirmasi: "Disetujui",
    //   file: "Link Here",
    // },
  ];


  const ProgKhs = [
    {
      semester_aktif: "1",
      sks: "22",
      sks_kumulatif: "22",
      ip: "3.5",
      ip_kumulatif: "3.5",
      status_konfirmasi: "Disetujui",
      file: "Link Here",
    },
    {
      semester_aktif: "2",
      sks: "24",
      sks_kumulatif: "46",
      ip: "3.5",
      ip_kumulatif: "3.5",
      status_konfirmasi: "Disetujui",
      file: "Link Here",
    },
    {
      semester_aktif: "3",
      sks: "18",
      sks_kumulatif: "64",
      ip: "3.5",
      ip_kumulatif: "3.5",
      status_konfirmasi: "Disetujui",
      file: "Link Here",
    },
    {
      semester_aktif: "4",
      sks: "21",
      sks_kumulatif: "85",
      ip: "3.5",
      ip_kumulatif: "3.5",
      status_konfirmasi: "Disetujui",
      file: "Link Here",
    },
    {
      semester_aktif: "5",
      sks: "20",
      sks_kumulatif: "105",
      ip: "3.5",
      ip_kumulatif: "3.5",
      status_konfirmasi: "Belum Disetujui",
      file: "Link Here",
    },
    {
      semester_aktif: "6",
      sks: "22",
      sks_kumulatif: "22",
      ip: "3.5",
      ip_kumulatif: "3.5",
      status_konfirmasi: "Disetujui",
      file: "Link Here",
    },
    {
      semester_aktif: "7",
      sks: "24",
      sks_kumulatif: "46",
      ip: "3.5",
      ip_kumulatif: "3.5",
      status_konfirmasi: "Disetujui",
      file: "Link Here",
    },
    {
      semester_aktif: "8",
      sks: "18",
      sks_kumulatif: "64",
      ip: "3.5",
      ip_kumulatif: "3.5",
      status_konfirmasi: "Disetujui",
      file: "Link Here",
    },
    // {
    //   semester_aktif: "9",
    //   sks: "21",
    //   sks_kumulatif: "85",
    //   ip: "3.5",
    //   ip_kumulatif: "3.5",
    //   status_konfirmasi: "Disetujui",
    //   file: "Link Here",
    // },
    // {
    //   semester_aktif: "10",
    //   sks: "20",
    //   sks_kumulatif: "105",
    //   ip: "3.5",
    //   ip_kumulatif: "3.5",
    //   status_konfirmasi: "Belum Disetujui",
    //   file: "Link Here",
    // },
    // {
    //   semester_aktif: "11",
    //   sks: "22",
    //   sks_kumulatif: "22",
    //   ip: "3.5",
    //   ip_kumulatif: "3.5",
    //   status_konfirmasi: "Disetujui",
    //   file: "Link Here",
    // },
    // {
    //   semester_aktif: "12",
    //   sks: "24",
    //   sks_kumulatif: "46",
    //   ip: "3.5",
    //   ip_kumulatif: "3.5",
    //   status_konfirmasi: "Disetujui",
    //   file: "Link Here",
    // },
    // {
    //   semester_aktif: "13",
    //   sks: "18",
    //   sks_kumulatif: "64",
    //   ip: "3.5",
    //   ip_kumulatif: "3.5",
    //   status_konfirmasi: "Disetujui",
    //   file: "Link Here",
    // },
    // {
    //   semester_aktif: "14",
    //   sks: "21",
    //   sks_kumulatif: "85",
    //   ip: "3.5",
    //   ip_kumulatif: "3.5",
    //   status_konfirmasi: "Disetujui",
    //   file: "Link Here",
    // },
  ];

  const ProgPkl = [
    {
      nilai: "A",
      semester: "6",
      semester_aktif: "6",
      status_konfirmasi: "Disetujui",
      file: "Link Here",
    },

  ];
  
  const ProgSkripsi = [
    {
      nilai: "A",
      semester: "8",
      semester_aktif: "8",
      status_konfirmasi: "Belum Disetujui",
      tanggal: "12/12/2025",
      file: "Link Here",
    },

  ];
  

export {ProgIrs, ProgKhs, ProgPkl, ProgSkripsi}